/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedClinicRouteRouteImport } from './routes/_authenticated/_clinic/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSinAccesoRouteImport } from './routes/_authenticated/sin-acceso'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalReservarRouteImport } from './routes/portal.reservar'
import { Route as PortalTratamientosRouteImport } from './routes/portal.tratamientos'
import { Route as AuthenticatedClinicAgendaRouteImport } from './routes/_authenticated/_clinic/agenda'
import { Route as AuthenticatedClinicComplianceRouteImport } from './routes/_authenticated/_clinic/compliance'
import { Route as AuthenticatedClinicDashboardRouteImport } from './routes/_authenticated/_clinic/dashboard'
import { Route as AuthenticatedClinicDominioEmailRouteImport } from './routes/_authenticated/_clinic/dominio-email'
import { Route as AuthenticatedClinicEquipoRouteImport } from './routes/_authenticated/_clinic/equipo'
import { Route as AuthenticatedClinicPermisosRouteImport } from './routes/_authenticated/_clinic/permisos'
import { Route as AuthenticatedClinicPreferenciasRouteImport } from './routes/_authenticated/_clinic/preferencias'
import { Route as AuthenticatedClinicPruebasEmailRouteImport } from './routes/_authenticated/_clinic/pruebas-email'
import { Route as AuthenticatedClinicSandboxEmailRouteImport } from './routes/_authenticated/_clinic/sandbox-email'
import { Route as AuthenticatedClinicTratamientosRouteImport } from './routes/_authenticated/_clinic/tratamientos'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as AuthenticatedClinicPacientesIndexRouteImport } from './routes/_authenticated/_clinic/pacientes.index'
import { Route as AuthenticatedClinicPacientesPacienteIdRouteImport } from './routes/_authenticated/_clinic/pacientes.$pacienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicRouteRoute =
  AuthenticatedClinicRouteRouteImport.update({
    id: '/_clinic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinAccesoRoute = AuthenticatedSinAccesoRouteImport.update({
  id: '/sin-acceso',
  path: '/sin-acceso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReservarRoute = PortalReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTratamientosRoute = PortalTratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedClinicAgendaRoute =
  AuthenticatedClinicAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicComplianceRoute =
  AuthenticatedClinicComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicDashboardRoute =
  AuthenticatedClinicDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicDominioEmailRoute =
  AuthenticatedClinicDominioEmailRouteImport.update({
    id: '/dominio-email',
    path: '/dominio-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicEquipoRoute =
  AuthenticatedClinicEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPermisosRoute =
  AuthenticatedClinicPermisosRouteImport.update({
    id: '/permisos',
    path: '/permisos',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPreferenciasRoute =
  AuthenticatedClinicPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPruebasEmailRoute =
  AuthenticatedClinicPruebasEmailRouteImport.update({
    id: '/pruebas-email',
    path: '/pruebas-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicSandboxEmailRoute =
  AuthenticatedClinicSandboxEmailRouteImport.update({
    id: '/sandbox-email',
    path: '/sandbox-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicTratamientosRoute =
  AuthenticatedClinicTratamientosRouteImport.update({
    id: '/tratamientos',
    path: '/tratamientos',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicPacientesIndexRoute =
  AuthenticatedClinicPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPacientesPacienteIdRoute =
  AuthenticatedClinicPacientesPacienteIdRouteImport.update({
    id: '/pacientes/$pacienteId',
    path: '/pacientes/$pacienteId',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/portal/tratamientos': typeof PortalTratamientosRoute
  '/portal/': typeof PortalIndexRoute
  '/agenda': typeof AuthenticatedClinicAgendaRoute
  '/compliance': typeof AuthenticatedClinicComplianceRoute
  '/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/equipo': typeof AuthenticatedClinicEquipoRoute
  '/permisos': typeof AuthenticatedClinicPermisosRoute
  '/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/pacientes/': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/portal/tratamientos': typeof PortalTratamientosRoute
  '/portal': typeof PortalIndexRoute
  '/agenda': typeof AuthenticatedClinicAgendaRoute
  '/compliance': typeof AuthenticatedClinicComplianceRoute
  '/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/equipo': typeof AuthenticatedClinicEquipoRoute
  '/permisos': typeof AuthenticatedClinicPermisosRoute
  '/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/pacientes': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_clinic': typeof AuthenticatedClinicRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/portal/tratamientos': typeof PortalTratamientosRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/_clinic/agenda': typeof AuthenticatedClinicAgendaRoute
  '/_authenticated/_clinic/compliance': typeof AuthenticatedClinicComplianceRoute
  '/_authenticated/_clinic/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/_authenticated/_clinic/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/_authenticated/_clinic/equipo': typeof AuthenticatedClinicEquipoRoute
  '/_authenticated/_clinic/permisos': typeof AuthenticatedClinicPermisosRoute
  '/_authenticated/_clinic/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/_authenticated/_clinic/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/_authenticated/_clinic/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/_authenticated/_clinic/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/_clinic/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/_authenticated/_clinic/pacientes/': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/sitemap.xml'
    | '/onboarding'
    | '/sin-acceso'
    | '/portal/documentos'
    | '/portal/reservar'
    | '/portal/tratamientos'
    | '/portal/'
    | '/agenda'
    | '/compliance'
    | '/dashboard'
    | '/dominio-email'
    | '/equipo'
    | '/permisos'
    | '/preferencias'
    | '/pruebas-email'
    | '/sandbox-email'
    | '/tratamientos'
    | '/api/stripe/webhook'
    | '/pacientes/$pacienteId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/onboarding'
    | '/sin-acceso'
    | '/portal/documentos'
    | '/portal/reservar'
    | '/portal/tratamientos'
    | '/portal'
    | '/agenda'
    | '/compliance'
    | '/dashboard'
    | '/dominio-email'
    | '/equipo'
    | '/permisos'
    | '/preferencias'
    | '/pruebas-email'
    | '/sandbox-email'
    | '/tratamientos'
    | '/api/stripe/webhook'
    | '/pacientes/$pacienteId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/sitemap.xml'
    | '/_authenticated/_clinic'
    | '/_authenticated/onboarding'
    | '/_authenticated/sin-acceso'
    | '/portal/documentos'
    | '/portal/reservar'
    | '/portal/tratamientos'
    | '/portal/'
    | '/_authenticated/_clinic/agenda'
    | '/_authenticated/_clinic/compliance'
    | '/_authenticated/_clinic/dashboard'
    | '/_authenticated/_clinic/dominio-email'
    | '/_authenticated/_clinic/equipo'
    | '/_authenticated/_clinic/permisos'
    | '/_authenticated/_clinic/preferencias'
    | '/_authenticated/_clinic/pruebas-email'
    | '/_authenticated/_clinic/sandbox-email'
    | '/_authenticated/_clinic/tratamientos'
    | '/api/stripe/webhook'
    | '/_authenticated/_clinic/pacientes/$pacienteId'
    | '/_authenticated/_clinic/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_clinic': {
      id: '/_authenticated/_clinic'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClinicRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sin-acceso': {
      id: '/_authenticated/sin-acceso'
      path: '/sin-acceso'
      fullPath: '/sin-acceso'
      preLoaderRoute: typeof AuthenticatedSinAccesoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reservar': {
      id: '/portal/reservar'
      path: '/reservar'
      fullPath: '/portal/reservar'
      preLoaderRoute: typeof PortalReservarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/tratamientos': {
      id: '/portal/tratamientos'
      path: '/tratamientos'
      fullPath: '/portal/tratamientos'
      preLoaderRoute: typeof PortalTratamientosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/_clinic/agenda': {
      id: '/_authenticated/_clinic/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedClinicAgendaRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/compliance': {
      id: '/_authenticated/_clinic/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedClinicComplianceRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/dashboard': {
      id: '/_authenticated/_clinic/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicDashboardRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/dominio-email': {
      id: '/_authenticated/_clinic/dominio-email'
      path: '/dominio-email'
      fullPath: '/dominio-email'
      preLoaderRoute: typeof AuthenticatedClinicDominioEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/equipo': {
      id: '/_authenticated/_clinic/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedClinicEquipoRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/permisos': {
      id: '/_authenticated/_clinic/permisos'
      path: '/permisos'
      fullPath: '/permisos'
      preLoaderRoute: typeof AuthenticatedClinicPermisosRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/preferencias': {
      id: '/_authenticated/_clinic/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AuthenticatedClinicPreferenciasRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/pruebas-email': {
      id: '/_authenticated/_clinic/pruebas-email'
      path: '/pruebas-email'
      fullPath: '/pruebas-email'
      preLoaderRoute: typeof AuthenticatedClinicPruebasEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/sandbox-email': {
      id: '/_authenticated/_clinic/sandbox-email'
      path: '/sandbox-email'
      fullPath: '/sandbox-email'
      preLoaderRoute: typeof AuthenticatedClinicSandboxEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/tratamientos': {
      id: '/_authenticated/_clinic/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof AuthenticatedClinicTratamientosRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_clinic/pacientes/': {
      id: '/_authenticated/_clinic/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedClinicPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/pacientes/$pacienteId': {
      id: '/_authenticated/_clinic/pacientes/$pacienteId'
      path: '/pacientes/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AuthenticatedClinicPacientesPacienteIdRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
  }
}

interface AuthenticatedClinicRouteRouteChildren {
  AuthenticatedClinicAgendaRoute: typeof AuthenticatedClinicAgendaRoute
  AuthenticatedClinicComplianceRoute: typeof AuthenticatedClinicComplianceRoute
  AuthenticatedClinicDashboardRoute: typeof AuthenticatedClinicDashboardRoute
  AuthenticatedClinicDominioEmailRoute: typeof AuthenticatedClinicDominioEmailRoute
  AuthenticatedClinicEquipoRoute: typeof AuthenticatedClinicEquipoRoute
  AuthenticatedClinicPermisosRoute: typeof AuthenticatedClinicPermisosRoute
  AuthenticatedClinicPreferenciasRoute: typeof AuthenticatedClinicPreferenciasRoute
  AuthenticatedClinicPruebasEmailRoute: typeof AuthenticatedClinicPruebasEmailRoute
  AuthenticatedClinicSandboxEmailRoute: typeof AuthenticatedClinicSandboxEmailRoute
  AuthenticatedClinicTratamientosRoute: typeof AuthenticatedClinicTratamientosRoute
  AuthenticatedClinicPacientesPacienteIdRoute: typeof AuthenticatedClinicPacientesPacienteIdRoute
  AuthenticatedClinicPacientesIndexRoute: typeof AuthenticatedClinicPacientesIndexRoute
}

const AuthenticatedClinicRouteRouteChildren: AuthenticatedClinicRouteRouteChildren =
  {
    AuthenticatedClinicAgendaRoute: AuthenticatedClinicAgendaRoute,
    AuthenticatedClinicComplianceRoute: AuthenticatedClinicComplianceRoute,
    AuthenticatedClinicDashboardRoute: AuthenticatedClinicDashboardRoute,
    AuthenticatedClinicDominioEmailRoute: AuthenticatedClinicDominioEmailRoute,
    AuthenticatedClinicEquipoRoute: AuthenticatedClinicEquipoRoute,
    AuthenticatedClinicPermisosRoute: AuthenticatedClinicPermisosRoute,
    AuthenticatedClinicPreferenciasRoute: AuthenticatedClinicPreferenciasRoute,
    AuthenticatedClinicPruebasEmailRoute: AuthenticatedClinicPruebasEmailRoute,
    AuthenticatedClinicSandboxEmailRoute: AuthenticatedClinicSandboxEmailRoute,
    AuthenticatedClinicTratamientosRoute: AuthenticatedClinicTratamientosRoute,
    AuthenticatedClinicPacientesPacienteIdRoute:
      AuthenticatedClinicPacientesPacienteIdRoute,
    AuthenticatedClinicPacientesIndexRoute:
      AuthenticatedClinicPacientesIndexRoute,
  }

const AuthenticatedClinicRouteRouteWithChildren =
  AuthenticatedClinicRouteRoute._addFileChildren(
    AuthenticatedClinicRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClinicRouteRoute: typeof AuthenticatedClinicRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSinAccesoRoute: typeof AuthenticatedSinAccesoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClinicRouteRoute: AuthenticatedClinicRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSinAccesoRoute: AuthenticatedSinAccesoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteChildren {
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalReservarRoute: typeof PortalReservarRoute
  PortalTratamientosRoute: typeof PortalTratamientosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalReservarRoute: PortalReservarRoute,
  PortalTratamientosRoute: PortalTratamientosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
