/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AuthenticatedClinicRouteRouteImport } from './routes/_authenticated/_clinic/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSinAccesoRouteImport } from './routes/_authenticated/sin-acceso'
import { Route as ApiDemoResetRouteImport } from './routes/api.demo-reset'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp-webhook'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsDatosYSeguridadRouteImport } from './routes/docs.datos-y-seguridad'
import { Route as DocsPortalPacientesRouteImport } from './routes/docs.portal-pacientes'
import { Route as DocsPrimerosPasosRouteImport } from './routes/docs.primeros-pasos'
import { Route as DocsWhatsappRouteImport } from './routes/docs.whatsapp'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as PortalInicioRouteImport } from './routes/portal.inicio'
import { Route as AuthenticatedClinicAgendaRouteImport } from './routes/_authenticated/_clinic/agenda'
import { Route as AuthenticatedClinicComplianceRouteImport } from './routes/_authenticated/_clinic/compliance'
import { Route as AuthenticatedClinicDashboardRouteImport } from './routes/_authenticated/_clinic/dashboard'
import { Route as AuthenticatedClinicDominioEmailRouteImport } from './routes/_authenticated/_clinic/dominio-email'
import { Route as AuthenticatedClinicEquipoRouteImport } from './routes/_authenticated/_clinic/equipo'
import { Route as AuthenticatedClinicFinanzasRouteImport } from './routes/_authenticated/_clinic/finanzas'
import { Route as AuthenticatedClinicPermisosRouteImport } from './routes/_authenticated/_clinic/permisos'
import { Route as AuthenticatedClinicPreferenciasRouteImport } from './routes/_authenticated/_clinic/preferencias'
import { Route as AuthenticatedClinicPruebasEmailRouteImport } from './routes/_authenticated/_clinic/pruebas-email'
import { Route as AuthenticatedClinicRecordatoriosRouteImport } from './routes/_authenticated/_clinic/recordatorios'
import { Route as AuthenticatedClinicSandboxEmailRouteImport } from './routes/_authenticated/_clinic/sandbox-email'
import { Route as AuthenticatedClinicSuscripcionRouteImport } from './routes/_authenticated/_clinic/suscripcion'
import { Route as AuthenticatedClinicTratamientosRouteImport } from './routes/_authenticated/_clinic/tratamientos'
import { Route as AuthenticatedClinicWhatsappRouteImport } from './routes/_authenticated/_clinic/whatsapp'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as AuthenticatedClinicPacientesIndexRouteImport } from './routes/_authenticated/_clinic/pacientes.index'
import { Route as AuthenticatedClinicPacientesPacienteIdRouteImport } from './routes/_authenticated/_clinic/pacientes.$pacienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicRouteRoute =
  AuthenticatedClinicRouteRouteImport.update({
    id: '/_clinic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSinAccesoRoute = AuthenticatedSinAccesoRouteImport.update({
  id: '/sin-acceso',
  path: '/sin-acceso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDemoResetRoute = ApiDemoResetRouteImport.update({
  id: '/api/demo-reset',
  path: '/api/demo-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDatosYSeguridadRoute = DocsDatosYSeguridadRouteImport.update({
  id: '/datos-y-seguridad',
  path: '/datos-y-seguridad',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPortalPacientesRoute = DocsPortalPacientesRouteImport.update({
  id: '/portal-pacientes',
  path: '/portal-pacientes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPrimerosPasosRoute = DocsPrimerosPasosRouteImport.update({
  id: '/primeros-pasos',
  path: '/primeros-pasos',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWhatsappRoute = DocsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DocsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInicioRoute = PortalInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedClinicAgendaRoute =
  AuthenticatedClinicAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicComplianceRoute =
  AuthenticatedClinicComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicDashboardRoute =
  AuthenticatedClinicDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicDominioEmailRoute =
  AuthenticatedClinicDominioEmailRouteImport.update({
    id: '/dominio-email',
    path: '/dominio-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicEquipoRoute =
  AuthenticatedClinicEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicFinanzasRoute =
  AuthenticatedClinicFinanzasRouteImport.update({
    id: '/finanzas',
    path: '/finanzas',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPermisosRoute =
  AuthenticatedClinicPermisosRouteImport.update({
    id: '/permisos',
    path: '/permisos',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPreferenciasRoute =
  AuthenticatedClinicPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPruebasEmailRoute =
  AuthenticatedClinicPruebasEmailRouteImport.update({
    id: '/pruebas-email',
    path: '/pruebas-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicRecordatoriosRoute =
  AuthenticatedClinicRecordatoriosRouteImport.update({
    id: '/recordatorios',
    path: '/recordatorios',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicSandboxEmailRoute =
  AuthenticatedClinicSandboxEmailRouteImport.update({
    id: '/sandbox-email',
    path: '/sandbox-email',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicSuscripcionRoute =
  AuthenticatedClinicSuscripcionRouteImport.update({
    id: '/suscripcion',
    path: '/suscripcion',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicTratamientosRoute =
  AuthenticatedClinicTratamientosRouteImport.update({
    id: '/tratamientos',
    path: '/tratamientos',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicWhatsappRoute =
  AuthenticatedClinicWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicPacientesIndexRoute =
  AuthenticatedClinicPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)
const AuthenticatedClinicPacientesPacienteIdRoute =
  AuthenticatedClinicPacientesPacienteIdRouteImport.update({
    id: '/pacientes/$pacienteId',
    path: '/pacientes/$pacienteId',
    getParentRoute: () => AuthenticatedClinicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/api/demo-reset': typeof ApiDemoResetRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/docs/datos-y-seguridad': typeof DocsDatosYSeguridadRoute
  '/docs/portal-pacientes': typeof DocsPortalPacientesRoute
  '/docs/primeros-pasos': typeof DocsPrimerosPasosRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/inicio': typeof PortalInicioRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/agenda': typeof AuthenticatedClinicAgendaRoute
  '/compliance': typeof AuthenticatedClinicComplianceRoute
  '/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/equipo': typeof AuthenticatedClinicEquipoRoute
  '/finanzas': typeof AuthenticatedClinicFinanzasRoute
  '/permisos': typeof AuthenticatedClinicPermisosRoute
  '/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/recordatorios': typeof AuthenticatedClinicRecordatoriosRoute
  '/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/suscripcion': typeof AuthenticatedClinicSuscripcionRoute
  '/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/whatsapp': typeof AuthenticatedClinicWhatsappRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/pacientes/': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/api/demo-reset': typeof ApiDemoResetRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/docs/datos-y-seguridad': typeof DocsDatosYSeguridadRoute
  '/docs/portal-pacientes': typeof DocsPortalPacientesRoute
  '/docs/primeros-pasos': typeof DocsPrimerosPasosRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/inicio': typeof PortalInicioRoute
  '/docs': typeof DocsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/agenda': typeof AuthenticatedClinicAgendaRoute
  '/compliance': typeof AuthenticatedClinicComplianceRoute
  '/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/equipo': typeof AuthenticatedClinicEquipoRoute
  '/finanzas': typeof AuthenticatedClinicFinanzasRoute
  '/permisos': typeof AuthenticatedClinicPermisosRoute
  '/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/recordatorios': typeof AuthenticatedClinicRecordatoriosRoute
  '/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/suscripcion': typeof AuthenticatedClinicSuscripcionRoute
  '/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/whatsapp': typeof AuthenticatedClinicWhatsappRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/pacientes': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/_clinic': typeof AuthenticatedClinicRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/sin-acceso': typeof AuthenticatedSinAccesoRoute
  '/api/demo-reset': typeof ApiDemoResetRoute
  '/api/health': typeof ApiHealthRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/docs/datos-y-seguridad': typeof DocsDatosYSeguridadRoute
  '/docs/portal-pacientes': typeof DocsPortalPacientesRoute
  '/docs/primeros-pasos': typeof DocsPrimerosPasosRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/inicio': typeof PortalInicioRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/_clinic/agenda': typeof AuthenticatedClinicAgendaRoute
  '/_authenticated/_clinic/compliance': typeof AuthenticatedClinicComplianceRoute
  '/_authenticated/_clinic/dashboard': typeof AuthenticatedClinicDashboardRoute
  '/_authenticated/_clinic/dominio-email': typeof AuthenticatedClinicDominioEmailRoute
  '/_authenticated/_clinic/equipo': typeof AuthenticatedClinicEquipoRoute
  '/_authenticated/_clinic/finanzas': typeof AuthenticatedClinicFinanzasRoute
  '/_authenticated/_clinic/permisos': typeof AuthenticatedClinicPermisosRoute
  '/_authenticated/_clinic/preferencias': typeof AuthenticatedClinicPreferenciasRoute
  '/_authenticated/_clinic/pruebas-email': typeof AuthenticatedClinicPruebasEmailRoute
  '/_authenticated/_clinic/recordatorios': typeof AuthenticatedClinicRecordatoriosRoute
  '/_authenticated/_clinic/sandbox-email': typeof AuthenticatedClinicSandboxEmailRoute
  '/_authenticated/_clinic/suscripcion': typeof AuthenticatedClinicSuscripcionRoute
  '/_authenticated/_clinic/tratamientos': typeof AuthenticatedClinicTratamientosRoute
  '/_authenticated/_clinic/whatsapp': typeof AuthenticatedClinicWhatsappRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/_clinic/pacientes/$pacienteId': typeof AuthenticatedClinicPacientesPacienteIdRoute
  '/_authenticated/_clinic/pacientes/': typeof AuthenticatedClinicPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/docs'
    | '/faq'
    | '/nosotros'
    | '/portal'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/onboarding'
    | '/sin-acceso'
    | '/api/demo-reset'
    | '/api/health'
    | '/api/whatsapp-webhook'
    | '/docs/datos-y-seguridad'
    | '/docs/portal-pacientes'
    | '/docs/primeros-pasos'
    | '/docs/whatsapp'
    | '/portal/$token'
    | '/portal/inicio'
    | '/docs/'
    | '/portal/'
    | '/agenda'
    | '/compliance'
    | '/dashboard'
    | '/dominio-email'
    | '/equipo'
    | '/finanzas'
    | '/permisos'
    | '/preferencias'
    | '/pruebas-email'
    | '/recordatorios'
    | '/sandbox-email'
    | '/suscripcion'
    | '/tratamientos'
    | '/whatsapp'
    | '/api/stripe/webhook'
    | '/pacientes/$pacienteId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/faq'
    | '/nosotros'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/onboarding'
    | '/sin-acceso'
    | '/api/demo-reset'
    | '/api/health'
    | '/api/whatsapp-webhook'
    | '/docs/datos-y-seguridad'
    | '/docs/portal-pacientes'
    | '/docs/primeros-pasos'
    | '/docs/whatsapp'
    | '/portal/$token'
    | '/portal/inicio'
    | '/docs'
    | '/portal'
    | '/agenda'
    | '/compliance'
    | '/dashboard'
    | '/dominio-email'
    | '/equipo'
    | '/finanzas'
    | '/permisos'
    | '/preferencias'
    | '/pruebas-email'
    | '/recordatorios'
    | '/sandbox-email'
    | '/suscripcion'
    | '/tratamientos'
    | '/whatsapp'
    | '/api/stripe/webhook'
    | '/pacientes/$pacienteId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/docs'
    | '/faq'
    | '/nosotros'
    | '/portal'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/_authenticated/_clinic'
    | '/_authenticated/onboarding'
    | '/_authenticated/sin-acceso'
    | '/api/demo-reset'
    | '/api/health'
    | '/api/whatsapp-webhook'
    | '/docs/datos-y-seguridad'
    | '/docs/portal-pacientes'
    | '/docs/primeros-pasos'
    | '/docs/whatsapp'
    | '/portal/$token'
    | '/portal/inicio'
    | '/docs/'
    | '/portal/'
    | '/_authenticated/_clinic/agenda'
    | '/_authenticated/_clinic/compliance'
    | '/_authenticated/_clinic/dashboard'
    | '/_authenticated/_clinic/dominio-email'
    | '/_authenticated/_clinic/equipo'
    | '/_authenticated/_clinic/finanzas'
    | '/_authenticated/_clinic/permisos'
    | '/_authenticated/_clinic/preferencias'
    | '/_authenticated/_clinic/pruebas-email'
    | '/_authenticated/_clinic/recordatorios'
    | '/_authenticated/_clinic/sandbox-email'
    | '/_authenticated/_clinic/suscripcion'
    | '/_authenticated/_clinic/tratamientos'
    | '/_authenticated/_clinic/whatsapp'
    | '/api/stripe/webhook'
    | '/_authenticated/_clinic/pacientes/$pacienteId'
    | '/_authenticated/_clinic/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  NosotrosRoute: typeof NosotrosRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  ApiDemoResetRoute: typeof ApiDemoResetRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_clinic': {
      id: '/_authenticated/_clinic'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClinicRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sin-acceso': {
      id: '/_authenticated/sin-acceso'
      path: '/sin-acceso'
      fullPath: '/sin-acceso'
      preLoaderRoute: typeof AuthenticatedSinAccesoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/demo-reset': {
      id: '/api/demo-reset'
      path: '/api/demo-reset'
      fullPath: '/api/demo-reset'
      preLoaderRoute: typeof ApiDemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/datos-y-seguridad': {
      id: '/docs/datos-y-seguridad'
      path: '/datos-y-seguridad'
      fullPath: '/docs/datos-y-seguridad'
      preLoaderRoute: typeof DocsDatosYSeguridadRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/portal-pacientes': {
      id: '/docs/portal-pacientes'
      path: '/portal-pacientes'
      fullPath: '/docs/portal-pacientes'
      preLoaderRoute: typeof DocsPortalPacientesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/primeros-pasos': {
      id: '/docs/primeros-pasos'
      path: '/primeros-pasos'
      fullPath: '/docs/primeros-pasos'
      preLoaderRoute: typeof DocsPrimerosPasosRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/whatsapp': {
      id: '/docs/whatsapp'
      path: '/whatsapp'
      fullPath: '/docs/whatsapp'
      preLoaderRoute: typeof DocsWhatsappRouteImport
      parentRoute: typeof DocsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inicio': {
      id: '/portal/inicio'
      path: '/inicio'
      fullPath: '/portal/inicio'
      preLoaderRoute: typeof PortalInicioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/_clinic/agenda': {
      id: '/_authenticated/_clinic/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedClinicAgendaRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/compliance': {
      id: '/_authenticated/_clinic/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedClinicComplianceRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/dashboard': {
      id: '/_authenticated/_clinic/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedClinicDashboardRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/dominio-email': {
      id: '/_authenticated/_clinic/dominio-email'
      path: '/dominio-email'
      fullPath: '/dominio-email'
      preLoaderRoute: typeof AuthenticatedClinicDominioEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/equipo': {
      id: '/_authenticated/_clinic/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedClinicEquipoRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/finanzas': {
      id: '/_authenticated/_clinic/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedClinicFinanzasRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/permisos': {
      id: '/_authenticated/_clinic/permisos'
      path: '/permisos'
      fullPath: '/permisos'
      preLoaderRoute: typeof AuthenticatedClinicPermisosRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/preferencias': {
      id: '/_authenticated/_clinic/preferencias'
      path: '/preferencias'
      fullPath: '/preferencias'
      preLoaderRoute: typeof AuthenticatedClinicPreferenciasRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/pruebas-email': {
      id: '/_authenticated/_clinic/pruebas-email'
      path: '/pruebas-email'
      fullPath: '/pruebas-email'
      preLoaderRoute: typeof AuthenticatedClinicPruebasEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/recordatorios': {
      id: '/_authenticated/_clinic/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof AuthenticatedClinicRecordatoriosRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/sandbox-email': {
      id: '/_authenticated/_clinic/sandbox-email'
      path: '/sandbox-email'
      fullPath: '/sandbox-email'
      preLoaderRoute: typeof AuthenticatedClinicSandboxEmailRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/suscripcion': {
      id: '/_authenticated/_clinic/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof AuthenticatedClinicSuscripcionRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/tratamientos': {
      id: '/_authenticated/_clinic/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof AuthenticatedClinicTratamientosRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/whatsapp': {
      id: '/_authenticated/_clinic/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedClinicWhatsappRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_clinic/pacientes/': {
      id: '/_authenticated/_clinic/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedClinicPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
    '/_authenticated/_clinic/pacientes/$pacienteId': {
      id: '/_authenticated/_clinic/pacientes/$pacienteId'
      path: '/pacientes/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AuthenticatedClinicPacientesPacienteIdRouteImport
      parentRoute: typeof AuthenticatedClinicRouteRoute
    }
  }
}

interface AuthenticatedClinicRouteRouteChildren {
  AuthenticatedClinicAgendaRoute: typeof AuthenticatedClinicAgendaRoute
  AuthenticatedClinicComplianceRoute: typeof AuthenticatedClinicComplianceRoute
  AuthenticatedClinicDashboardRoute: typeof AuthenticatedClinicDashboardRoute
  AuthenticatedClinicDominioEmailRoute: typeof AuthenticatedClinicDominioEmailRoute
  AuthenticatedClinicEquipoRoute: typeof AuthenticatedClinicEquipoRoute
  AuthenticatedClinicFinanzasRoute: typeof AuthenticatedClinicFinanzasRoute
  AuthenticatedClinicPermisosRoute: typeof AuthenticatedClinicPermisosRoute
  AuthenticatedClinicPreferenciasRoute: typeof AuthenticatedClinicPreferenciasRoute
  AuthenticatedClinicPruebasEmailRoute: typeof AuthenticatedClinicPruebasEmailRoute
  AuthenticatedClinicRecordatoriosRoute: typeof AuthenticatedClinicRecordatoriosRoute
  AuthenticatedClinicSandboxEmailRoute: typeof AuthenticatedClinicSandboxEmailRoute
  AuthenticatedClinicSuscripcionRoute: typeof AuthenticatedClinicSuscripcionRoute
  AuthenticatedClinicTratamientosRoute: typeof AuthenticatedClinicTratamientosRoute
  AuthenticatedClinicWhatsappRoute: typeof AuthenticatedClinicWhatsappRoute
  AuthenticatedClinicPacientesPacienteIdRoute: typeof AuthenticatedClinicPacientesPacienteIdRoute
  AuthenticatedClinicPacientesIndexRoute: typeof AuthenticatedClinicPacientesIndexRoute
}

const AuthenticatedClinicRouteRouteChildren: AuthenticatedClinicRouteRouteChildren =
  {
    AuthenticatedClinicAgendaRoute: AuthenticatedClinicAgendaRoute,
    AuthenticatedClinicComplianceRoute: AuthenticatedClinicComplianceRoute,
    AuthenticatedClinicDashboardRoute: AuthenticatedClinicDashboardRoute,
    AuthenticatedClinicDominioEmailRoute: AuthenticatedClinicDominioEmailRoute,
    AuthenticatedClinicEquipoRoute: AuthenticatedClinicEquipoRoute,
    AuthenticatedClinicFinanzasRoute: AuthenticatedClinicFinanzasRoute,
    AuthenticatedClinicPermisosRoute: AuthenticatedClinicPermisosRoute,
    AuthenticatedClinicPreferenciasRoute: AuthenticatedClinicPreferenciasRoute,
    AuthenticatedClinicPruebasEmailRoute: AuthenticatedClinicPruebasEmailRoute,
    AuthenticatedClinicRecordatoriosRoute:
      AuthenticatedClinicRecordatoriosRoute,
    AuthenticatedClinicSandboxEmailRoute: AuthenticatedClinicSandboxEmailRoute,
    AuthenticatedClinicSuscripcionRoute: AuthenticatedClinicSuscripcionRoute,
    AuthenticatedClinicTratamientosRoute: AuthenticatedClinicTratamientosRoute,
    AuthenticatedClinicWhatsappRoute: AuthenticatedClinicWhatsappRoute,
    AuthenticatedClinicPacientesPacienteIdRoute:
      AuthenticatedClinicPacientesPacienteIdRoute,
    AuthenticatedClinicPacientesIndexRoute:
      AuthenticatedClinicPacientesIndexRoute,
  }

const AuthenticatedClinicRouteRouteWithChildren =
  AuthenticatedClinicRouteRoute._addFileChildren(
    AuthenticatedClinicRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClinicRouteRoute: typeof AuthenticatedClinicRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSinAccesoRoute: typeof AuthenticatedSinAccesoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClinicRouteRoute: AuthenticatedClinicRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSinAccesoRoute: AuthenticatedSinAccesoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsDatosYSeguridadRoute: typeof DocsDatosYSeguridadRoute
  DocsPortalPacientesRoute: typeof DocsPortalPacientesRoute
  DocsPrimerosPasosRoute: typeof DocsPrimerosPasosRoute
  DocsWhatsappRoute: typeof DocsWhatsappRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDatosYSeguridadRoute: DocsDatosYSeguridadRoute,
  DocsPortalPacientesRoute: DocsPortalPacientesRoute,
  DocsPrimerosPasosRoute: DocsPrimerosPasosRoute,
  DocsWhatsappRoute: DocsWhatsappRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PortalRouteChildren {
  PortalTokenRoute: typeof PortalTokenRoute
  PortalInicioRoute: typeof PortalInicioRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalTokenRoute: PortalTokenRoute,
  PortalInicioRoute: PortalInicioRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  NosotrosRoute: NosotrosRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  ApiDemoResetRoute: ApiDemoResetRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
